site_name: Quraner Fariwala Documentation
site_description: Dignity-first governance, forensic documentation, and ethical distribution
site_author: MJ Ahmad
repo_url: https://github.com/mj-nexara/qfdocs

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    scheme: slate
    primary: indigo
    accent: cyan
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.action.edit

nav:
  - Home: index.md
  - Manifesto: manifesto.md
  - Governance:
      - Mission & Ethics: governance/mission-ethics.md
      - Board & Leadership: governance/board-leadership.md
      - Governance Policy: governance/governance-policy.md
      - Constitution: governance/constitution.md
  - Legal Ownership:
      - Director Declaration: legal-ownership/director-declaration_MJ-Ahmad.md
      - Legal Basis (Bangladesh): legal-ownership/legal-basis_BD.md
      - Legal Basis (International): legal-ownership/legal-basis_INT.md
      - Ownership Structure: legal-ownership/ownership-structure.yaml
      - DID Identity: legal-ownership/did-identity.md
  - Verifiable Manifest:
      - Identity Manifest: verifiable-manifest/mj-ahmad_identity_manifest_v1.3.1.json
      - Signed Manifest: verifiable-manifest/signed-manifest.json
      - Verification Report: verifiable-manifest/verify-report.json
      - LumID Config: verifiable-manifest/lumid-config.json
  - Contributor Ethics: nexara-integrations.md
  - Forensic Documentation:
      - Incidents:
          - Hasnabad School Incident: forensic-documentation/incidents/2021_Hasnabad_School_Incident.md
          - Fund Misuse Allegation: forensic-documentation/incidents/2022_Fund_Misuse_Allegation.md
          - Metadata: forensic-documentation/incidents/metadata.yaml
      - Audit Trails:
          - Financial Audit: forensic-documentation/audit-trails/financial-audit_2023.md
          - Contributor Traceability: forensic-documentation/audit-trails/contributor-traceability.yaml
      - Legal Responses:
          - Court Submissions: forensic-documentation/legal-responses/court-submissions/
          - Lawyer Letters: forensic-documentation/legal-responses/lawyer-letters/
          - Verdicts: forensic-documentation/legal-responses/verdicts/
  - Quran Research & Distribution:
      - Partner Institutions: quran-research-distribution/partner-institutions.md
  - Financial Claims Settlement:
      - Verified Creditors: financial-claims-settlement/verified-creditors.yaml
      - Payment Status: financial-claims-settlement/payment-status.md
      - Delay Compensation Policy: financial-claims-settlement/delay-compensation-policy.md
  - Public Reputation Shield:
      - False Allegation Tracker: public-reputation-shield/false-allegation-tracker.yaml
      - Reputation Monitoring Policy: public-reputation-shield/reputation-monitoring-policy.md
  - Monitoring & Research:
      - Monitoring Framework: monitoring-research-system/monitoring-framework.md
      - Research Methodology: monitoring-research-system/research-methodology.md
  - International Compliance:
      - Global Standards: international-compliance/global-standards.md
      - Multilingual Access Policy: international-compliance/multilingual-access-policy.md
      - Cross-Border Defense: international-compliance/cross-border-defense.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji

plugins:
  - search
  - git-revision-date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mj-nexara