site_name: Quraner Fariwala – Research, Printing & Distribution of the Holy Quran
site_url: https://mj-nexara.github.io/qfdocs
repo_url: https://github.com/mj-nexara/qfdocs
repo_name: mj-nexara/qfdocs

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - search.highlight

plugins:
  - search
  - git-revision-date-localized
  - awesome-pages

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: index.md
  - Quran Project:
      - Printing Method: quran/printing-method.md
      - Validation & Endorsements: quran/validation.md
      - Distribution Framework: quran/distribution.md
      - Comparative Analysis: quran/comparison.md
  - Investment & Governance:
      - Strategic Plan: investment/plan.md
      - Intake Policy: investment/intake-policy.md
      - Dividend Structure: investment/dividend-structure.md
      - Investor Records: investment/investor-records.md
  - 2023 Incident:
      - Overview: incident/overview.md
      - Tarek Jamil: incident/person-01_tarek-jamil/README.md
      - Hossain: incident/person-02_hossain/README.md
      - Hamidullah: incident/person-03_hamidullah/README.md
  - Legal & Ownership:
      - Licensing: legal/licensing.md
      - Ownership Declaration: legal/ownership.md
      - Audit Trail: legal/audit-trail.md
  - Media & Outreach:
      - Testimonials: media/testimonials.md
      - Gallery: media/gallery.md
      - Social Posts: media/social-posts.md
  - Contributors:
      - Onboarding Guide: contributors/onboarding.md
      - Contributor Metadata: contributors/metadata.yaml
